name: EmbeddingScratchwork

channels:
  - conda-forge

dependencies:
  - python=3.13
  - backoff
  - blake3
  - dulwich
  - numpy
  - openai<1
  - orjson
  - requests>=2.31.0
  - safetensors

  # For testing
  - attrs
  - parameterized
  - pytest
  - pytest-sugar

  # For linting
  - flake8
  - flake8-pyproject
  - isort
  - pylint

  # For notebooks
  - graphviz
  - ipykernel
  - jupyterlab>=4
  - jupyter-collaboration
  - nbdime
  - python-graphviz
  - tabulate

  # PyPI
  - pip
  - pip:
    - pylint-actions
    - pylint-exit
    - subaudit
