name: EmbeddingScratchwork

channels:
  - conda-forge

dependencies:
  - python =3.13
  - backoff
  - dulwich
  - numpy
  - openai >=0.28.1,<1
  - orjson
  - requests >=2.32.0
  - safetensors

  # For `openai[embeddings]`, whose extra dependencies are not listed for the
  # conda-forge downstream `openai` package since v0.28.1. For details, see:
  # https://github.com/conda-forge/openai-feedstock/pull/218
  - matplotlib-base
  - openpyxl >=3.0.7
  - pandas >=1.2.3
  - pandas-stubs >=1.0.1.11
  - plotly
  - scikit-learn >=1.0.2
  - scipy
  - tenacity >=8.0.1

  # For testing
  - attrs
  - parameterized
  - pytest
  - pytest-sugar

  # For linting
  - flake8
  - flake8-pyproject
  - isort
  - pylint

  # For notebooks
  - graphviz
  - ipykernel
  - jupyterlab >=4
  - jupyter-collaboration
  - nbdime
  - python-graphviz
  - tabulate

  # PyPI
  - pip
  - pip:
    - blake3 >=1
    - pylint-actions
    - pylint-exit
    - subaudit
