name: EmbeddingScratchwork

channels:
  - conda-forge

dependencies:
  - python=3.11
  - backoff
  - dulwich
  - numpy
  - openai
  - orjson
  - requests
  - safetensors
  - tiktoken

  # For development
  - attrs
  - flake8
  - isort
  - parameterized
  - pylint

  # For notebooks
  - graphviz
  - ipykernel
  - jupyterlab>=4
  - jupyter-collaboration
  - nbdime
  - python-graphviz
  - tabulate

  # PyPI
  - pip
  - pip:
    - blake3
    - pylint-actions
    - pylint-exit
    - pylint-sarif-unofficial
    - subaudit
