name: Check Markdown

on:
  push:
  pull_request:
  schedule:
    - cron: '0 16 * * *'

jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v5
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          config-file: .github/workflows/markdown-links-config.json

  markdownlint-cli2:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v5
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: '**/*.md'
